//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsDocuments
    {
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Description { get; set; }
        public byte[] Documents { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.Guid> RegistrationUser { get; set; }
        public Nullable<System.Guid> ModificationUser { get; set; }
        public string Procedure { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
